### ISSUE TITLE
Fix structural zeros code in Get.MLE.p1.FW

### ISSUE THREAD

**Issue by lizgross** [csprock/DMBHGraphs#14]
We want to change this block of code:

  if (!is.null(zeros.bidir) || !is.null(zeros.dir)){
    mzeros = 1-Get.Configuration.Matrix.p1.FW(zeros.dir, zeros.bidir)
    mzeros[,,1,1] = 1
    startM[,,,] = startM * mzeros

so that mzeros[i,j,1,1] = 0 if zeros.dir and zeros.bidir contain all three configs i-->j, j-->i, i<-->j and that mzeros[i,j,1,1] = 1 otherwise.

**Comment by csprock** [comment]
So for clarification, mzeros is the complement of the structural zeros graph, so putting a zero in (i,j,1,1) (which corresponds to no edge between i and j) would be forbidding the sampling of the non-existence of an edge between i and j?

**Comment by csprock** [comment]
I think something like this piece of logic should work

```
  adj.dir <- igraph::get.adjacency(zeros.dir)
  adj.bidir <- igraph::get.adjacency(zeros.bidir)
  
  # 1 in zeros_where[i,j] should correspond to all three configs
  zeros_where <- t(adj.dir)*adj.dir*adj.bidir
  
  mzeros <- Get.Configuration.Matrix.p1.FW(zeros.dir, zeros.bidir)
  
  n <- igraph::vcount(zeros.dir)
  for (i in 1:n){
    for (j in 1:n){
      mzeros[i,j,1,1] <- zeros_where[i,j]
    }
  }
```

**Comment by csprock** [comment]
Added working function and unit test case.

**Comment by lizgross** [comment]
Yes, that is correct.

Also, the code in the file looks good. To optimize, we can 1) use a table of all 1's instead of calling the configuration matrix function and 2) have j go from i:n in the loop rather than 1:n
