### ISSUE TITLE
Rename `get_directed_piece` to `generate_type_2_move`

### ISSUE THREAD

**Issue by csprock** [csprock/DMBHGraphs#25]
Rename `get_directed_piece` to `generate_type_2_move`
https://github.com/csprock/DMBHGraphs/blob/master/R/move_pieces.R#L193

**Comment by imanishbarnwal** [comment]
Hello @csprock, can I take this issue?

**Comment by csprock** [comment]
Hi @imanishbarnwal, thanks for your interest in contributing. I will first have to check with my colleague about what our contribution policy is.

**Comment by imanishbarnwal** [comment]
> Hi @imanishbarnwal, thanks for your interest in contributing. I will first have to check with my colleague about what our contribution policy is.

Okay, sure.
