### ISSUE TITLE
check validation in type 2 move code

### ISSUE THREAD

**Issue by csprock** [csprock/DMBHGraphs#27]
Check that the checks applied in the get_directed_piece/ type 2 code (https://github.com/csprock/DMBHGraphs/blob/master/R/move_pieces.R#L185) are consistent with those in the original code (https://github.com/csprock/DMBHGraphs/blob/master/R/p1AndMoreWalk.R#L1010)

**Comment by csprock** [comment]
Found some differences between my implementation of the validation and the original. The original code uses different nomenclature for the directed and undirected components, my notation is taken from the paper. 

* the original code checks that the edges to add contain no bidirected edges, not just that the graph is simple (https://github.com/csprock/DMBHGraphs/blob/master/R/p1AndMoreWalk.R#L1021)
* the check to make sure the edges to add are not in the directed component after the first set of edges has been removed takes the undirected version of each of the components while my implementation uses directed versions of everything (https://github.com/csprock/DMBHGraphs/blob/master/R/p1AndMoreWalk.R#L1024)
* the check that the edges to add do not add any edges to the undirected component (or the component representing bidirected edges) is the same except the "byname" is used in the graph intersection function (https://github.com/csprock/DMBHGraphs/blob/master/R/p1AndMoreWalk.R#L1028)

**Comment by csprock** [comment]
In this part of the code (https://github.com/csprock/DMBHGraphs/blob/master/R/move_pieces.R#L169) if b is already undirected, then what I have works. However if it is directed, we need to apply the check for bidirected edges. 

Under what circumstances are we going make undirected moves?

**Comment by lizgross** [comment]
> Found some differences between my implementation of the validation and the original. The original code uses different nomenclature for the directed and undirected components, my notation is taken from the paper.
> 
> * the original code checks that the edges to add contain no bidirected edges, not just that the graph is simple (https://github.com/csprock/DMBHGraphs/blob/master/R/p1AndMoreWalk.R#L1021)

**Let's change new code so that the edges to add contain no bidirected edges**

> * the check to make sure the edges to add are not in the directed component after the first set of edges has been removed takes the undirected version of each of the components while my implementation uses directed versions of everything (https://github.com/csprock/DMBHGraphs/blob/master/R/p1AndMoreWalk.R#L1024)

**I think we need to do a check like in the original.  We want to make sure (1) we are not adding any edges that already exist and (2) we are not creating a bidirected edge.**

> * the check that the edges to add do not add any edges to the undirected component (or the component representing bidirected edges) is the same except the "byname" is used in the graph intersection function (https://github.com/csprock/DMBHGraphs/blob/master/R/p1AndMoreWalk.R#L1028)

I think you need to use "byname" else things awry.

**Comment by lizgross** [comment]
> In this part of the code (https://github.com/csprock/DMBHGraphs/blob/master/R/move_pieces.R#L169) if b is already undirected, then what I have works. However if it is directed, we need to apply the check for bidirected edges.
> 
> Under what circumstances are we going make undirected moves?

b should always be directed

**Comment by csprock** [comment]
I think the checks are included here: https://github.com/csprock/DMBHGraphs/blob/master/R/p1AndMoreWalk.R#L131. If the input graphs are formatted correctly, so should samples taken from them and b should always be directed: https://github.com/csprock/DMBHGraphs/blob/master/R/move_pieces.R#L195

**Comment by csprock** [comment]
I kind of want to leave out the "byname='auto'" for now and once we have everything working with unnamed vertices, then we go back and update the entire code-base for named vertices in one sweep.

I remember just named vertices causing problems earlier and I don't want to introduce any complications until we've got everything working with just vertex ID indices.
