### ISSUE TITLE
Get rid of code referring to HL algorithm

### ISSUE THREAD

**Issue by lizgross** [csprock/DMBHGraphs#3]
Get rid of Get.Configuration.Matrix.p1.HL and remove all functionality for models: p1.HLalg.recip.nzconst, p1.HLalg.recip.zero, but leave the function Get.MLE.p1.HL

**Comment by csprock** [comment]
Do you want to actual remove Get.Configuration.Matrix.p1.HL and Get.MLE.p1.HL or leave the functions in so the user can specify using the pre-computed MLE from p1.HL?

**Comment by csprock** [comment]
Currently the model default for Estimate.p.Value is "p1.HLalg.recip.nzconst", what should we set this to?
