### ISSUE TITLE
resursive_partition() returns NA when passed a single edge

### ISSUE THREAD

**Issue by csprock** [csprock/DMBHGraphs#32]
`recursive_partition()` can return a list containing NA's when passed a single edge. We also need to decide how we want to handle cases where the sample returns a single edge since you can't make a move without at least two edges. 

Steps to reproduce:
```
gudir <- igraph::graph_from_edgelist(
  matrix(c(
    c(2, 6),
    c(3, 5)
  ), ncol = 2, byrow = TRUE), directed = TRUE)

set.seed(42)
r <- sample_edges(gudir)
partitions <- recursive_partition(r)
```

**Comment by csprock** [comment]
One option would be to simple return the singleton edge and let downstream functions decide how to handle it. Another option would be to return NULL and throw out those values, leaving only the sampled sets that have at least two edges. If somehow you ended up sampling all singleton sets, just return NULL for the entire move. 

I also think we should enforce some constraints on the input graphs to avoid this happening like graphs with single edges or less than 4 vertices.

**Comment by csprock** [comment]
Another option would be to prevent sample_edges from returning singletons, perhaps adding a recursive call to sample_edges until n >= 2, but then it might get stuck if there is only 1 edge so sample, in which case we need to prevent such graphs from being input at all.

**Comment by csprock** [comment]
Found the problem in https://github.com/csprock/DMBHGraphs/blob/master/R/move_pieces.R#L19. If ecount(g) = 2, then that line runs as `sample(2, 1)`, in which is telling the `sample` function to sample from 1:2, and so a sample of size 1 can be selected. 

Also, obviously, if ecount(g) = 2, then that line will return 1 each time.

**Comment by csprock** [comment]
Recommend we add a check during the initial validation stage to make sure that n > 3 and m > 1: https://github.com/csprock/DMBHGraphs/blob/master/R/p1AndMoreWalk.R#L131

**Comment by lizgross** [comment]
Here's what I would do:

Add n==1 in the "or" check on line 42 of move_pieces.  However, let's check the logical implications of this first.

**Comment by csprock** [comment]
We should also consider the pathological case where the empty graph is passed.
