### ISSUE TITLE
Indices of configuration matrix appear switched

### ISSUE THREAD

**Issue by csprock** [csprock/DMBHGraphs#5]
https://github.com/csprock/DMBHGraphs/blob/master/R/p1AndMoreWalk.R#L792
https://github.com/csprock/DMBHGraphs/blob/master/R/p1AndMoreWalk.R#L793

Per our discussion, the index U[i,j,1,2] corresponds to an edge i --> j, while U[i,j,2,1] corresponds to an edge i <-- j. However, the order of these appears to be switched in the actual implementation. I found this while implementing unit tests using the original configuration, tests for the unreciprocated edges were failing, and switching the indices fixed the tests.

**Comment by lizgross** [comment]
Let's make sure that the indices of the MLE returned from get.MLE and the indices of get.Configuration.Matrix match up.

**Comment by csprock** [comment]
Change the following in the Get.Configuration.Matrix.p1.FW() function in the get_mle.R file on lines 59-60:

x[i,j,2,1]=1
x[j,i,1,2]=1

to

x[i,j,1,2]=1
x[j,i,2,1]=1

**Comment by csprock** [comment]
Fixed this per our discussion.
