### ISSUE TITLE
Warning for vertex check that is performed in Get.MLE.p1.FW

### ISSUE THREAD

**Issue by lizgross** [csprock/DMBHGraphs#8]
The code below checks whether the directed and undirected graphs have the same number of vertices, if not, the code adds isolated vertices to the graph with the least number of vertices.

nd = vcount(gdir)
  nb = vcount(gbidir)
  n=max(nd,nb)
  if (nd>nb){
    gbidir = add.vertices(gbidir,nd-nb)
  }
  else if (nd<nb){
    gdir = add.vertices(gdir,nb-nd)
  }

**Comment by csprock** [comment]
I'll try to break the vertex-balancing function into its own helper-function since we use that functionality often. Then I'll add a warning that is separate from the function.

**Comment by csprock** [comment]
Done.
