### ISSUE TITLE
Make input graph validation function

### ISSUE THREAD

**Issue by lizgross** [csprock/DMBHGraphs#9]
For example, we can use this to check zeros.dir and zeros.bidir are simple

**Comment by lizgross** [comment]
See #Error Checking comment in Estimate.p.Value

**Comment by csprock** [comment]
Here is the validation logic I've got:

For the input graphs that represent the directed and non-reciprocated edges, the following checks are applied in the following order:
* check that graph is directed
* check that there are no reciprocated edges
* check that the undirected skeleton of the graph is simple (no multi-edges in the same direction)

For the input graphs that represent the bidirected edges, the following checks are applied in the following order:
* check that graph is undirected
* check that graph is simple

**Comment by csprock** [comment]
Done.
